"""
Module 8: Compound Engineering & Agent Swarms
Demonstrates multi-agent team workflows:
1. Cognitive Role Division (Planner, Implementer, Reviewer)
2. Git Worktree Workspace Isolation
3. Subagent Prompt Isolation & Clean Context Hygiene
4. Telemetry-Driven Self-Improvement Loops
"""

import ast
import json
import os
import subprocess
import tempfile
from datetime import datetime, timezone

class SubagentPromptIsolator:
    """
    Give each subagent a focused spec slice instead of the parent chat.

    Real Claude Code subagents already start with a clean context window.
    This helper is the course stand-in: keep lines that mention the
    subtask name, allowed scope, or non-goals, and drop the rest.
    """
    def extract_sub_spec(self, master_spec: str, subtask_name: str) -> str:
        lines = master_spec.splitlines()
        filtered = [l for l in lines if subtask_name.lower() in l.lower() or "allowed scope" in l.lower() or "non-goals" in l.lower()]
        if not filtered:
            return f"SUB-SPEC FOR {subtask_name}: Execute task within strict scope limits."
        return "\n".join(filtered)

class MultiAgentTeamSimulator:
    """
    Planner -> Implementer -> Reviewer handoff plus telemetry.

    The implementer writes into a TemporaryDirectory, not a real git
    worktree. The printed `git worktree add` line is labelled
    NOT EXECUTED so the demo does not pretend it isolated a worktree.
    """

    def __init__(self, workspace_root: str):
        self.workspace_root = os.path.abspath(workspace_root)
        self.isolator = SubagentPromptIsolator()
        self.telemetry_log = os.path.join(self.workspace_root, "telemetry.jsonl")

    def run_planner(self, spec_text: str) -> dict:
        """Return two named subtasks. The spec_text is accepted so the planner API matches a real agent."""
        plan = {
            "subtasks": [
                {"name": "auth_component", "target_file": "auth.py", "action": "Implement JWT validation"},
                {"name": "test_suite", "target_file": "test_auth.py", "action": "Write unit tests for JWT"}
            ]
        }
        return plan

    def run_implementer_in_worktree(self, subtask: dict, master_spec: str) -> bool:
        """Write one scoped Python file from a focused spec slice. Isolated by the temp workspace, not git."""
        focused_spec = self.isolator.extract_sub_spec(master_spec, subtask["name"])
        target = os.path.join(self.workspace_root, subtask["target_file"])
        
        # Simulate clean worktree edit
        with open(target, "w", encoding="utf-8") as f:
            f.write(f"# Auto-generated by Implementer Subagent for {subtask['name']}\n# Focused Spec: {focused_spec[:50]}\ndef validate_jwt(token):\n    return True\n")
        return True

    def run_reviewer(self, target_file: str) -> bool:
        """Cheap reviewer: the file exists and defines validate_jwt. AST and scope are checked in main()."""
        target = os.path.join(self.workspace_root, target_file)
        if not os.path.exists(target):
            return False
        with open(target, "r", encoding="utf-8") as f:
            content = f.read()
        return "def validate_jwt" in content

if __name__ == "__main__":
    print("=" * 72)
    print("MODULE 8 DEMO: COMPOUND ENGINEERING & MULTI-AGENT TEAMS")
    print("=" * 72)

    allowed_scope = {"auth.py", "test_auth.py"}
    master_spec = (
        "SPEC: JWT Auth System\n"
        "Allowed Scope: auth.py, test_auth.py\n"
        "auth_component: Implement JWT validation\n"
        "test_suite: Write unit tests for JWT\n"
        "Non-goals: network calls and dependency changes"
    )

    with tempfile.TemporaryDirectory(prefix="module_08_team_") as workspace:
        sim = MultiAgentTeamSimulator(workspace)
        spec_path = os.path.join(workspace, "SPEC.md")
        try:
            with open(spec_path, "w", encoding="utf-8") as spec_file:
                spec_file.write(master_spec)
            with open(spec_path, "r", encoding="utf-8") as spec_file:
                supplied_spec = spec_file.read()
        except OSError as exc:
            print(f"[FAIL] Could not prepare the temporary SPEC.md: {exc}")
            raise SystemExit(1)

        print("[Planner Subagent (Architect)] Analyzing requirement...")
        plan = sim.run_planner(supplied_spec)
        subtasks = plan.get("subtasks") if isinstance(plan, dict) else None
        plan_valid = (
            isinstance(subtasks, list)
            and bool(subtasks)
            and all(
                isinstance(subtask, dict)
                and {"name", "target_file", "action"} <= subtask.keys()
                for subtask in subtasks
            )
        )
        if not plan_valid:
            print("[FAIL] Planner returned an invalid or empty subtask plan.")
            raise SystemExit(1)
        print(f"  [PASS] Plan Generated: {len(subtasks)} micro-subtasks allocated.")

        print(
            "[Implementer Subagent (Coder)] Executing simulated edits in a "
            "temporary sandbox..."
        )
        print(
            "  Claude Code project subagents are defined in "
            ".claude/agents/<name>.md with frontmatter `isolation: worktree`."
        )
        print(
            "  [Illustrative command - NOT EXECUTED] "
            "git worktree add -b agent-worktree ./worktree-dir main"
        )

        implementation_results = []
        for subtask in subtasks:
            try:
                implemented = sim.run_implementer_in_worktree(
                    subtask, supplied_spec
                )
            except (KeyError, OSError) as exc:
                print(
                    f"  [FAIL] Implementer could not complete "
                    f"'{subtask.get('name', '<unknown>')}': {exc}"
                )
                raise SystemExit(1)
            implementation_results.append(implemented)
            if not implemented:
                print(
                    f"  [FAIL] Implementer returned failure for "
                    f"'{subtask['name']}'."
                )
                raise SystemExit(1)
            print(
                f"  [PASS] Simulated isolated edit completed for "
                f"'{subtask['name']}'."
            )

        print(
            "[Reviewer Subagent (Auditor)] Auditing Implementer output "
            "against SPEC.md..."
        )
        review_results = []
        planned_targets = {subtask["target_file"] for subtask in subtasks}
        for subtask in subtasks:
            target_file = subtask["target_file"]
            target_path = os.path.abspath(os.path.join(workspace, target_file))
            reviewer_passed = sim.run_reviewer(target_file)
            try:
                with open(target_path, "r", encoding="utf-8") as source_file:
                    ast.parse(source_file.read(), filename=target_path)
                syntax_valid = True
            except (OSError, SyntaxError):
                syntax_valid = False
            scope_compliant = (
                target_file in allowed_scope
                and os.path.commonpath([workspace, target_path]) == workspace
            )
            review_results.append(
                reviewer_passed and syntax_valid and scope_compliant
            )

        produced_targets = {
            name for name in os.listdir(workspace) if name.endswith(".py")
        }
        full_scope_compliance = (
            planned_targets == produced_targets
            and planned_targets <= allowed_scope
        )
        all_reviews_passed = (
            all(implementation_results)
            and all(review_results)
            and full_scope_compliance
        )
        if not all_reviews_passed:
            print(
                "  [FAIL] Review failed: reviewer, AST, or scope validation "
                "did not pass."
            )
            raise SystemExit(1)
        print(
            "  [PASS] Review Passed: AST syntax valid, scope compliance confirmed."
        )

        task_name = "jwt_auth_multi_agent_handoff"
        telemetry_record = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "task": task_name,
            "subtasks": len(subtasks),
            "implementation_passed": all(implementation_results),
            "review_passed": all_reviews_passed,
        }
        try:
            with open(sim.telemetry_log, "a", encoding="utf-8") as telemetry_file:
                telemetry_file.write(json.dumps(telemetry_record) + "\n")
            with open(sim.telemetry_log, "r", encoding="utf-8") as telemetry_file:
                recorded_telemetry = json.loads(telemetry_file.readlines()[-1])
        except (OSError, IndexError, json.JSONDecodeError) as exc:
            print(f"[FAIL] Telemetry could not be recorded and verified: {exc}")
            raise SystemExit(1)

        telemetry_verified = (
            recorded_telemetry == telemetry_record
            and os.path.basename(sim.telemetry_log) == "telemetry.jsonl"
        )
        if not telemetry_verified:
            print("[FAIL] Telemetry read-back did not match the recorded task.")
            raise SystemExit(1)
        print(
            f"[Self-Improvement Telemetry] Recorded task '{task_name}' into "
            f"'{os.path.basename(sim.telemetry_log)}'."
        )

    print(
        "\nMODULE 8 DEMO COMPLETE: Multi-Agent Handoff & Telemetry Verified!"
    )
